### ISSUE TITLE
Duplication bug found

### ISSUE THREAD

**Issue by SykoUSS** [Rocologo/BagOfGold#133] opened 2022-10-27 14:32 UTC
Place item in chest inventory, hover over item press f to place in offhand. Item is the place in both offhand and first inventory slot

**Comment by SykoUSS** [comment] 2022-10-27 14:40
If item is left in offhand and duplicate is moved to chest again the player can continue pressing f to duplicate in inventory

**Comment by SykoUSS** [comment] 2022-10-27 14:40
If item is left in offhand and duplicate is moved to chest again the player can continue pressing f to duplicate in inventory

**Comment by Rocologo** [comment] 2022-10-29 11:04
Confirmed. This will be fixed fast.  I have not known how to make this action HOTBAR_MOVE_AND_READD until now and this is the reason for this bug. It is simple to fix now. Thank you for reporting this bug.

**Comment by Rocologo** [comment] 2022-11-21 07:13
This is solve in next release

**Comment by Rocologo** [comment] 2022-11-24 11:50
Fixed in V4.5.0 notice that you will need my new libray CustomItemsLib 

https://www.spigotmc.org/resources/customitemslib.106375/

**Closed by Rocologo** 2022-11-24 11:50 UTC
Labels: bug
