### ISSUE TITLE
Bypassing the 10000 gold limit

### ISSUE THREAD

**Issue by Arttale** [Rocologo/BagOfGold#88] opened 2020-03-03 13:50 UTC
Dropping multiple bags of gold on the ground makes them automatically stack
eg 5000+3000=8000
but sometimes it bypasses the 10000 gold limit when it does.
When transferred to inventory it sometimes adds to a bagsofgold in the inventory if present and also adds to that number, also it can easily bypass 10000 gold.
This works especially well with stacked bags of gold (the issue I opened last time)
This essentially allows infinite storage in one item slot.

To recreate it, all you can to do is to drop the bagofgold from your inventory and exit your inventory as soon as you are about to pick it up.

**Comment by Rocologo** [comment] 2020-04-01 06:25
I cant reproduce the problem. Please explain what you do step by step, very detailed.

**Comment by Arttale** [comment] 2020-04-20 14:28
It was a while since I came back to this, currently playing on a different server without this plugin.
At the time I reported this bug, I didn't really refine the method, it was really more of a chance thing at the time. I did refine the method later on. basically you have to drop the money bag on the ground and move the player, and have the player pick it up prematurely. I got a old video that you can see here: https://drive.google.com/open?id=1hFF0LYCIX_G8DpFq5kLtVMC6zHyd1LAK
ps: It'll also allow you to exponentially dupe money in creative by middle-clicking.
pps: Also sorry couldn't help you with the testing back then, I don't check my emails that often

**Comment by Arttale** [comment] 2020-04-20 14:40
also sorry for the large uncompressed mp4 file

**Comment by Rocologo** [comment] 2020-05-18 17:37
I think this is fixed in newest version?

**Closed** 2020-05-18 17:40 UTC
Labels: More information needed
