### ISSUE TITLE
lacing bag of gold in enderchest /chest /shulker chest makes it useless. cannot deposit or anything.

### ISSUE THREAD

**Issue by SirAbeyance** [Rocologo/BagOfGold#29] opened 2018-08-21 18:04 UTC
spigot: fe3ab0d-0611294 MC:1.13 API 1.13-R0.1-snapshot
latest version of bag of gol you have.

If bag of gold is put in any type of chest, and then taken out players can not deposit, withdraw.
If you then combine it with another bag it seems as if the bag went to negative value.

Also, the Lore is not hidden. I'm using latest protocollib available.

**Comment by Rocologo** [comment] 2018-08-21 18:20
Thank you for creating a ticket.

I have tested this on my test-server, and I was not able reproduce the problem??? I have tested this on a normal chest and on an ender chest. I could place bags in the chests combine bags in the chest and take them out and they still works as they should.

So to help you we need to find the difference between my test-server and you server. (I cant solve a bug I cant see/reproduce).

Please enable debug using "/bag debug" and "/mh debug" (both plugins) and restart your server and login and put a bag in a chect and take it out again (make some operations) and then show me the full server log from start until you have done the operations.

**Comment by Rocologo** [comment] 2018-08-21 18:35
and please use pasebin.com :-)

**Comment by SirAbeyance** [comment] 2018-08-22 12:59
When putting the item in the chest, i can still see the item and take it, but the value became 0.

https://pastebin.com/vYm6m0MH

**Comment by Rocologo** [comment] 2018-08-22 13:40
I checked your log, you are using ProtocolLib for mc 1.12.2, update to protocollib 4.4.0-snapshot

**Comment by SirAbeyance** [comment] 2018-08-22 13:52
The Lore is indeed fixed.

https://pastebin.com/EpVFa9QU

The other issues remain.

**Comment by Rocologo** [comment] 2018-08-22 17:28
Thank you. 

I see the balance problems in the log.

I have found one difference. I use PerWorldInventory and you dont. I will have to check this. To see if I can reproduce the problem.

**Comment by Rocologo** [comment] 2018-08-22 17:42
I removed PerWorldInventory and MultiVerse and NOW I can replicate the problem! 

I have newer tried to remove Multiverse before , so I dont know if it is PerWorldInventory or Multiverse which give me problems.

**Comment by Rocologo** [comment] 2018-08-22 18:04
I think I have found the problem in BagOfGold and fixed in in build 142
https://fractal.lindegaard.one:8181/job/BagOfGold/142/

Please test and the me know the result! as soon as posible. If it is fixed i will make a fast release, because this is a serious bug

**Comment by SirAbeyance** [comment] 2018-08-22 18:28
Did a little testing, and it seems to work. I'll do more testing later on and let you know.

**Comment by Rocologo** [comment] 2018-08-22 19:33
V2.0.4 released.

**Comment by SirAbeyance** [comment] 2018-08-22 19:34
It all seems to work fine now.
Thank you.

**Comment by Rocologo** [comment] 2018-08-22 19:34
thank for helping with the testing!

**Closed by Rocologo** 2018-08-22 19:33 UTC
