### ISSUE TITLE
Banker depost/withdraw text invisible

### ISSUE THREAD

**Issue by AnthonyPaulO** [Rocologo/BagOfGold#110] opened 2020-08-18 18:30 UTC
Latest spigot/bagofgold/cizitzens as of today, issue had been posted in discussion forum over a month ago. Create banker, right click banker, and banker displays text while the withdraw/deposit text is invisible.

![2020-08-18_14 25 30](https://user-images.githubusercontent.com/9335216/90551215-02013e00-e15f-11ea-9b0d-10d719735e1e.png)

**Comment by Rocologo** [comment] 2020-08-18 18:37
As stated on the frontpage bugs must be reported on Github, not the forums. I dont follow all discussions on the forums. I dont have the time to follow the forums. 

How does your config look like?

**Comment by AnthonyPaulO** [comment] 2020-08-18 18:48
> As stated on the frontpage bugs must be reported on Github, not the forums. I dont follow all discussions on the forums. I dont have the time to follow the forums.
> 
> How does your config look like?

It's default config, I create a folder, download spigot and plugins (BagOfGold, Citizens, and Vault) and run it; no changes to config whatsoever. Are you not seeing this? No optifine either, just plain vanilla.

**Comment by Rocologo** [comment] 2020-08-18 18:51
Im using the default config too... and i dont see this problem. From what I know now I have no way of guessing where the problem is.

**Comment by AnthonyPaulO** [comment] 2020-08-18 18:56
Strange, I reset my minecraft config settings to default just now and still the same issue. I'll try a new spigot install from scratch and see...

**Comment by Rocologo** [comment] 2020-08-18 18:59
Its actually a while since I have tried that myself and I dont have time to test this until the weekend. If you do the test and have succes to reproduce the problem i wiil of cause have to the test as well so i can fknd the problem.

**Comment by AnthonyPaulO** [comment] 2020-08-18 19:06
> Its actually a while since I have tried that myself and I dont have time to test this until the weekend. If you do the test and have succes to reproduce the problem i wiil of cause have to the test as well so i can fknd the problem.

UPDATE: tried brand new install of spigot with latest of each plugin as of today (BagOfGold, Citizens, and Vault) with complete reset of minecraft settings using vanilla 1.16.2 and still have the same issue with the BagOfGold links being invisible. My main instance where I first noticed the problem I also have GriefPrevention as well, and those links appear just fine in chat. Very strange...

**Comment by Rocologo** [comment] 2020-08-18 19:10
Yes. Thats very strange. My problem is thats it is extremely hard to find a bug, which i cant reproduce. I cant make a fix and if i try something i can test the solution.

I can see on the pic that there is a problem somewhere. No doubt about that.

**Comment by Rocologo** [comment] 2020-08-18 19:13
PS i use GP on my production server too, i dont think this is the problem. 

Maybe protocollib? Or a chat plugin? Do you use EssentialsX?

**Comment by AnthonyPaulO** [comment] 2020-08-18 20:38
I use protocollib on my server instance, but I did clean installs with only the 3 plugins I mentioned and still have the same issue. My son's laptop has the same issue and I just checked another PC I use for arcades and the same issue. Perhaps you should make a survey on the discussions thread to see who else has the same issue?

**Comment by AnthonyPaulO** [comment] 2020-08-24 01:44
> Please test newest build
> 
> https://fractal.lindegaard.one:8181/job/BagOfGold/
> 
> and let me know if it works for you?

Woohoo! Works like a charm! If you don't mind my asking, out of curiosity as a fellow programmer, why were you unable to see the bug and I was able to?

**Comment by Amblyopia** [comment] 2022-01-02 03:14
I just tried this with the latest build (520) and it's still not working on my 1.18.1 server.

**Comment by Rocologo** [comment] 2022-04-17 06:40
I think this is fixed in latest release 4.1.3.  I added a debug line as well. If you still have the problem I need to see the debug information when you click at the BankManager.

**Closed** 2022-07-03 10:56 UTC
Labels: Fixed - To be tested
